config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'pages#index'
  get 'pages/help'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :topics
  
  get 'favorites/index'
  post '/favorites', to: 'favorites#create'
  delete '/favorites', to: 'favorites#destroy'
  
  delete '/deletes', to: 'deletes#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/delete.rb
class Delete < ApplicationRecord
  belongs_to :user
  belongs_to :topic
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :topic
  
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :user_id, presence: true
  validates :description, presence: true
  validates :image, presence: true
  
  belongs_to :user

  mount_uploader :image, ImageUploader
  
  has_many :favorites
  has_many :favorite_users, through: :favorites, source: 'user'
  #topicをいいねしている全てのユーザー（id）を取得します
  has_many :deletes
  #削除機能
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
  
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}+\z/
  validates :password, presence: true, format: {with: VALID_PASSWORD_REGEX}

  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}
  
  validates :name, presence: true, length: { maximum: 15}

  has_secure_password
  
  has_many :topics
  
  has_many :favorites
  has_many :favorite_topics, through: :favorites, source: 'topic'
  
  has_many :deletes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :info, :warning, :danger

  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/controllers/deletes_controller.rb
class DeletesController < ApplicationController
  def destroy
    delete = Delete.new
    delete = Delete.find_by(user_id: current_user.id, topic_id: params[:topic_id])
    delete.destroy
    flash[:success] = "お気に入りを解除しました"
    redirect_to topics_path
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorite_topics = current_user.favorite_topics
    #現在のユーザのいいねした投稿を代入する
  end

  def create
    favorite = Favorite.new
    #Favariteクラスのインスタンスfavoriteを生成する
    favorite.user_id = current_user.id
    #favorite.user_idに現在ログインしているuserのidを代入する
    favorite.topic_id = params[:topic_id]
    #いいねしたTopicのidを取得する
    
    if favorite.save
      redirect_to topics_path, success: 'お気に入りに登録しました'
    else
      redirect_to topics_path, danger: 'お気に入りに登録に失敗しました'
    end
  end
  
  def destroy
    favorite = Favorite.find_by(user_id: current_user.id, topic_id: params[:topic_id])
    favorite.destroy if favorite.present?
    flash[:success] = "お気に入りを解除しました"
    redirect_to topics_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  
  def help
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_path, success: 'ログインに成功しました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_url, info: 'ログアウトしました'
  end

  private
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all.includes(:favorite_users)
    # 全てのtopicを取得する→投稿一覧画面へ :favorite_usersはモデル
  end
  
  def new
    @topic = Topic.new
    # Topicのnewアクション→投稿画面へ
  end

  def create
    @topic = current_user.topics.new(topic_params)
    # topic_params以下    current_user.topics(topic_params)　現在のユーザーのtopics(topic_params)を@topicに代入
    # t.integer :user_id
    # t.string :description
    # t.string :image

    if @topic.save
      redirect_to topics_path, success: '投稿に成功しました'     #@topicに格納成功したらtopics_pathへ飛ぶ
    else
      flash.now[:danger] = "投稿に失敗しました"          #失敗したらnewアクション
      render :new
    end
  end

  private
  def topic_params
    params.require(:topic).permit(:image, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: '登録が完了しました'
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new
    end
  end

  private
  def user_params
  params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deletes_helper.rb
module DeletesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @favorite_topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <%= image_tag topic.image.url %>
            <div style="display:flex">
              <div class="left_box">
              <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
              </div>
              <div class="right_box">
              <%= topic.favorites.count %>
              </div>
            </div>
            <p class="topic-text">
              <%= topic.description %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pictgram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>

    <nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
      <div class="container">
        <%= link_to root_path do %>
          <span><%= image_tag "icons/logo.png", class: "navbar-brand" %></span>
        <% end %>
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li>
              <%= link_to favorites_index_path do %>
               <%= image_tag 'icons/heart.png' %>
              <% end %>
            </li>
            <li>
            <li>
              <%= link_to new_topic_path do %>
                <%= image_tag 'icons/camera.png' %>
              <% end %>
            </li>
            </li>
            <li>
              <%= link_to logout_path, method: :delete do %>
                <%= image_tag "icons/logout.png" %>
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to new_user_path do %>
                <%= image_tag "icons/register.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to login_path do %>
                <%= image_tag "icons/login.png" %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>
    <%= yield %>
    <script>
  $(function(){
    $(".alert").fadeOut(5000);
  });
</script>
</html>

app/views/pages/help.html.erb
<h1>ヘルプページです</h1>

app/views/pages/index.html.erb
<div class="top-hero-wrapper text-center">
  <div class="container top-hero-container">
    <h1 class="text-white">Make you Happy</h1>
    <h2 class="text-white">Pictgram is a service that you can post photos.</h2>
    <h2 class="text-white">デプロイ</h2>
    <div class="row">
       <div class="col-md-offset-3 col-md-3">
        <%= link_to 'Sign in', new_user_path, class: 'btn btn-block btn-white' %>
       </div>
       <div class="col-md-3">
        <%= link_to 'Log in', login_path, class: 'btn btn-block btn-white' %>
       </div>
    </div>
  </div>
</div>

app/views/topics/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <%= image_tag topic.image.url %>
            <% if !topic.favorite_users.include?(current_user) %> 
            <!-- 偽だった場合に処理をする。　このtopicにログインしているユーザーのid(favorite_users)が存在しなかったら-->
              <%= link_to favorites_path(topic_id: topic.id), method: :post do %>
                <%= image_tag 'icons/heart-black.png', class: 'topic-index-icon' %>　<!-- 存在しなかった場合 -->
              <% end %>
            <% else %>
              <%= link_to favorites_path(topic_id: topic.id), method: :delete do %>
                <i class="fa fa-heart fa-2x heart-red"></i><!-- 存在した場合 --><!-- いいねした時-->
                <%= topic.favorite_users.count %>
              <% end %>
            <% end %>
            <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
            <p class="topic-text">
              <%= topic.description %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<div class="topic-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Add Picture</h1>
        <%= form_for @topic do |f| %>
            <div class="form-group">
              <%= f.label :image %>
              <%= f.file_field :image%>
            </div>
            <div class="form-group">
              <%= f.label :description %>
              <%= f.text_area :description, class: 'form-control' %>
            </div>
          <% if logged_in? %>  
           <%= f.submit '投稿', class: 'btn btn-black btn-block' %>
          <% end %> 
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">Sign in</h1>
        <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label :name, class: 'text-white' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email, class: 'text-white' %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password, class: 'text-white' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation, class: 'text-white' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

          <%= f.submit "登録", class: 'btn-block btn-white' %>
        <% end %>
        <%= link_to 'ログインはこちら', login_path, class: 'text-white' %>
      </div>
    </div>
  </div>
</div>